name: Sync to Google Sheets

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -X POST https://onboardblkoutnxt.supabase.co/functions/v1/sync-to-sheets \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" 